services:
  fastai-lab:
    build: ./env
    image: fastai-course-v25
    container_name: fastai-container
    ports:
      - "8888:8888"
    volumes:
      - .:/home/fastuser/project

    working_dir: /home/fastuser/project

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    shm_size: '8gb'
    restart: unless-stopped
